services:
  genshin:
    build: .
    container_name: genshin-dataset-builder
    tty: true        # <-- ADD THIS
    stdin_open: true # <-- ADD THIS (interactive)
    environment:
      HF_TOKEN: "hf_xxxxx"
    volumes:
      - .:/app
    command: python3 temp.py
